import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ requireUserProfile: vi.fn(), can: vi.fn(), createProjectSubmittalThroughCoreApi: vi.fn(), mutateProjectSubmittalThroughCoreApi: vi.fn(), linkProjectSubmittalDocumentThroughCoreApi: vi.fn(), unlinkProjectSubmittalDocumentThroughCoreApi: vi.fn(), revalidatePath: vi.fn() }))
vi.mock('next/cache', () => ({ revalidatePath: mocks.revalidatePath })); vi.mock('@third-code-erp/auth', () => ({ requireUserProfile: mocks.requireUserProfile, can: mocks.can })); vi.mock('@/lib/erp-core-client', () => ({ createProjectSubmittalThroughCoreApi: mocks.createProjectSubmittalThroughCoreApi, mutateProjectSubmittalThroughCoreApi: mocks.mutateProjectSubmittalThroughCoreApi, linkProjectSubmittalDocumentThroughCoreApi: mocks.linkProjectSubmittalDocumentThroughCoreApi, unlinkProjectSubmittalDocumentThroughCoreApi: mocks.unlinkProjectSubmittalDocumentThroughCoreApi }))
import { createProjectSubmittal, linkProjectSubmittalDocument, transitionProjectSubmittal, unlinkProjectSubmittalDocument, updateProjectSubmittal } from './actions'
const PROJECT_ID = '33333333-3333-4333-8333-333333333333'; const SUBMITTAL_ID = '44444444-4444-4444-8444-444444444444'; const DOCUMENT_ID = '66666666-6666-4666-8666-666666666666'; const LINK_ID = '88888888-8888-4888-8888-888888888888'; const REQUEST_ID = '55555555-5555-4555-8555-555555555555'; const USER_ID = '11111111-1111-4111-8111-111111111111'; const PROFILE = { user: { id: USER_ID }, tenantId: '22222222-2222-4222-8222-222222222222', role: 'pm', email: 'pm@example.test', fullName: 'PM' }
const entry = (status = 'draft', version = 1) => ({ id: SUBMITTAL_ID, projectId: PROJECT_ID, submittalNumber: 'SUB-0001', title: 'HVAC', description: 'Drawings', specSection: '', discipline: '', planReference: '', dueDate: null, status, submissionNotes: '', reviewNotes: '', rejectionReason: '', requestedBy: USER_ID, assignedTo: null, submittedAt: status === 'draft' ? null : '2026-09-10T00:00:00.000Z', submittedBy: status === 'draft' ? null : USER_ID, reviewStartedAt: null, reviewStartedBy: null, reviewedAt: null, reviewedBy: null, version, createdAt: '2026-09-10T00:00:00.000Z', updatedAt: '2026-09-10T00:00:00.000Z' })
function createForm() { const form = new FormData(); form.set('projectId', PROJECT_ID); form.set('clientRequestId', REQUEST_ID); form.set('title', 'HVAC'); form.set('description', 'Drawings'); form.set('specSection', ''); form.set('discipline', ''); form.set('planReference', ''); form.set('dueDate', ''); form.set('assignedTo', ''); return form }
describe('project submittal server actions', () => { beforeEach(() => { vi.clearAllMocks(); mocks.requireUserProfile.mockResolvedValue(PROFILE); mocks.can.mockReturnValue(true); mocks.createProjectSubmittalThroughCoreApi.mockResolvedValue({ ok: true, data: { projectId: PROJECT_ID, created: true, changed: true, submittal: entry() } }); mocks.mutateProjectSubmittalThroughCoreApi.mockResolvedValue({ ok: true, data: { projectId: PROJECT_ID, changed: true, submittal: entry('submitted', 2) } }) })
  it('creates through Core and retains request token', async () => { await expect(createProjectSubmittal({ ok: true }, createForm())).resolves.toEqual({ ok: true, success: 'SUB-0001 created.' }); expect(mocks.createProjectSubmittalThroughCoreApi).toHaveBeenCalledWith(expect.objectContaining({ clientRequestId: REQUEST_ID })) })
  it('routes update and submit actions', async () => { const update = createForm(); update.set('submittalId', SUBMITTAL_ID); update.set('expectedVersion', '1'); await expect(updateProjectSubmittal({ ok: true }, update)).resolves.toEqual({ ok: true, success: 'Submittal updated.' }); expect(mocks.mutateProjectSubmittalThroughCoreApi).toHaveBeenCalledWith(PROJECT_ID, SUBMITTAL_ID, 'update', expect.objectContaining({ expectedVersion: 1 })); const submit = new FormData(); submit.set('projectId', PROJECT_ID); submit.set('submittalId', SUBMITTAL_ID); submit.set('target', 'submit'); submit.set('expectedVersion', '2'); submit.set('submissionNotes', 'Revision 2'); await expect(transitionProjectSubmittal({ ok: true }, submit)).resolves.toEqual({ ok: true, success: 'Submittal submitted.' }) })
  it('fails closed for unauthorized creation', async () => { mocks.can.mockReturnValue(false); await expect(createProjectSubmittal({ ok: true }, createForm())).resolves.toMatchObject({ ok: false, error: expect.stringContaining('permission') }); expect(mocks.createProjectSubmittalThroughCoreApi).not.toHaveBeenCalled() })
  it('routes CDE link and unlink actions through Core with the parent version', async () => {
    mocks.linkProjectSubmittalDocumentThroughCoreApi.mockResolvedValue({ ok: true, data: { projectId: PROJECT_ID, submittalId: SUBMITTAL_ID, changed: true, submittalVersion: 2, link: { id: LINK_ID } } })
    const link = new FormData(); link.set('projectId', PROJECT_ID); link.set('submittalId', SUBMITTAL_ID); link.set('documentId', DOCUMENT_ID); link.set('role', 'plan'); link.set('caption', 'M-202'); link.set('expectedVersion', '1'); link.set('clientRequestId', REQUEST_ID)
    await expect(linkProjectSubmittalDocument({ ok: true }, link)).resolves.toEqual({ ok: true, success: 'Document linked to submittal.' })
    expect(mocks.linkProjectSubmittalDocumentThroughCoreApi).toHaveBeenCalledWith(PROJECT_ID, SUBMITTAL_ID, expect.objectContaining({ documentId: DOCUMENT_ID, expectedVersion: 1 }))
    mocks.unlinkProjectSubmittalDocumentThroughCoreApi.mockResolvedValue({ ok: true, data: { projectId: PROJECT_ID, submittalId: SUBMITTAL_ID, changed: true, submittalVersion: 3, linkId: LINK_ID } })
    const unlink = new FormData(); unlink.set('projectId', PROJECT_ID); unlink.set('submittalId', SUBMITTAL_ID); unlink.set('linkId', LINK_ID); unlink.set('expectedVersion', '2')
    await expect(unlinkProjectSubmittalDocument({ ok: true }, unlink)).resolves.toEqual({ ok: true, success: 'Document unlinked from submittal.' })
    expect(mocks.unlinkProjectSubmittalDocumentThroughCoreApi).toHaveBeenCalledWith(PROJECT_ID, SUBMITTAL_ID, LINK_ID, { expectedVersion: 2 })
  })
})
