import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, test } from 'node:test'

const temporaryDirectories = []
const script = resolve('scripts/assert-empty-schema-diff.mjs')

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true }),
    ),
  )
})

async function reportFile(contents) {
  const directory = await mkdtemp(join(tmpdir(), 'third-code-erp-schema-diff-'))
  temporaryDirectories.push(directory)
  const path = join(directory, 'report')
  await writeFile(path, contents, 'utf8')
  return path
}

function run(reportPath) {
  return spawnSync(process.execPath, [script, reportPath], { encoding: 'utf8' })
}

test('passes an empty structured Supabase schema diff', async () => {
  const path = await reportFile(JSON.stringify({ diff: '\n' }))

  const result = run(path)

  assert.equal(result.status, 0)
  assert.match(
    result.stdout,
    /PASS local database and migration-built shadow schema are identical/,
  )
})

test('fails a structured report that contains schema drift', async () => {
  const path = await reportFile(JSON.stringify({ diff: 'grant select on public.users to anon;' }))

  const result = run(path)

  assert.equal(result.status, 1)
  assert.match(result.stderr, /FAIL local database differs from the migration-built shadow schema/)
})

test('fails closed when a structured report omits the diff field', async () => {
  const path = await reportFile(JSON.stringify({ message: 'Diff complete.' }))

  const result = run(path)

  assert.equal(result.status, 1)
  assert.match(result.stderr, /must contain a string diff field/)
})

test('continues to accept legacy empty SQL reports', async () => {
  const path = await reportFile('-- generated by Supabase\n\n/* no schema changes */\n')

  const result = run(path)

  assert.equal(result.status, 0)
})
