import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { and, desc, eq } from 'drizzle-orm'
import { requireUserProfile, can } from '@third-code-erp/auth'
import { db } from '@third-code-erp/database'
import {
  projects,
  users,
  weeklyReports,
} from '@third-code-erp/database/schema'
import { generateThisWeekReport } from './actions'

export const metadata: Metadata = { title: 'Weekly reports' }

interface PageProps {
  params: Promise<{ id: string }>
}

interface SnapshotShape {
  overall_pct?: number
  tasks_completed?: unknown[]
  open_punchlist_count?: number
  schedule_variance_days?: number
}

// Lightweight "time ago" — keeps the table dense; we deliberately avoid
// pulling in a date-fns dep for one line.
function timeAgo(d: Date | string): string {
  const ms = Date.now() - new Date(d).getTime()
  const sec = Math.round(ms / 1000)
  if (sec < 60) return `${sec}s ago`
  const min = Math.round(sec / 60)
  if (min < 60) return `${min}m ago`
  const hr = Math.round(min / 60)
  if (hr < 24) return `${hr}h ago`
  const day = Math.round(hr / 24)
  if (day < 30) return `${day}d ago`
  const mo = Math.round(day / 30)
  if (mo < 12) return `${mo}mo ago`
  return `${Math.round(mo / 12)}y ago`
}

function formatWeekEnding(d: Date | string): string {
  return new Date(d).toLocaleDateString('en-PH', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

export default async function ProjectReportsPage({ params }: PageProps) {
  const { id } = await params
  const profile = await requireUserProfile()

  const [project] = await db
    .select({ id: projects.id, name: projects.name })
    .from(projects)
    .where(
      and(eq(projects.id, id), eq(projects.tenant_id, profile.tenantId))
    )
    .limit(1)

  if (!project) notFound()

  // Reports + generator name. Join via a single query so we don't N+1
  // on small lists.
  const rows = await db
    .select({
      id: weeklyReports.id,
      week_ending: weeklyReports.week_ending,
      generated_at: weeklyReports.generated_at,
      snapshot: weeklyReports.snapshot,
      generator_name: users.full_name,
      generator_email: users.email,
    })
    .from(weeklyReports)
    .leftJoin(users, eq(weeklyReports.generated_by, users.id))
    .where(
      and(
        eq(weeklyReports.tenant_id, profile.tenantId),
        eq(weeklyReports.project_id, id)
      )
    )
    .orderBy(desc(weeklyReports.week_ending))

  const canGenerate = can(profile.role, 'precon.manage_checklist')

  return (
    <div>
      <div className="page-header">
        <p className="page-eyebrow">
          <Link
            href={`/projects/${id}`}
            style={{ color: 'inherit', textDecoration: 'none' }}
          >
            Projects · {project.name}
          </Link>
        </p>
        <div className="page-toolbar">
          <div>
            <h1 className="page-title">Weekly reports</h1>
            <p className="page-subtitle">
              Auto-generated weekly snapshots — progress, completed tasks,
              open punchlist, schedule variance. Print-ready in one click.
            </p>
          </div>
          {canGenerate && (
            <form
              action={async () => {
                'use server'
                const result = await generateThisWeekReport(id)
                if (result.id) {
                  redirect(`/weekly-report/${result.id}`)
                }
              }}
              target="_blank"
            >
              <button
                type="submit"
                style={{
                  padding: '8px 16px',
                  borderRadius: '6px',
                  fontSize: '0.875rem',
                  fontWeight: 600,
                  background: 'var(--color-navy-700, #1F3864)',
                  color: 'white',
                  border: 'none',
                  cursor: 'pointer',
                  whiteSpace: 'nowrap',
                }}
              >
                Generate this week’s report
              </button>
            </form>
          )}
        </div>
      </div>

      <div className="card">
        <div className="card-header">
          <h2 className="card-title">All reports ({rows.length})</h2>
        </div>
        {rows.length === 0 ? (
          <div className="card-empty">
            No weekly reports yet.
            {canGenerate ? ' Click “Generate this week” to create the first one.' : ''}
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Week ending</th>
                <th>Generated by</th>
                <th className="numeric">Overall %</th>
                <th className="numeric">Tasks</th>
                <th className="numeric">Punchlist</th>
                <th className="numeric">Variance</th>
                <th>Generated</th>
                <th style={{ textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => {
                const snap = (r.snapshot ?? {}) as SnapshotShape
                const overall =
                  typeof snap.overall_pct === 'number' ? snap.overall_pct : 0
                const tasksCount = Array.isArray(snap.tasks_completed)
                  ? snap.tasks_completed.length
                  : 0
                const punchlist = Math.max(0, snap.open_punchlist_count ?? 0)
                const variance =
                  typeof snap.schedule_variance_days === 'number'
                    ? snap.schedule_variance_days
                    : 0
                const varianceLabel =
                  variance === 0
                    ? '—'
                    : variance > 0
                      ? `+${variance}d`
                      : `${variance}d`
                const varianceColor =
                  variance < 0
                    ? 'var(--color-red-700, #b91c1c)'
                    : variance > 0
                      ? 'var(--color-green-700, #15803d)'
                      : 'var(--color-neutral-500)'
                const generator =
                  r.generator_name ?? r.generator_email ?? 'System'

                return (
                  <tr key={r.id}>
                    <td style={{ fontWeight: 600 }}>
                      {formatWeekEnding(r.week_ending)}
                    </td>
                    <td className="muted">{generator}</td>
                    <td className="numeric">{overall.toFixed(1)}%</td>
                    <td className="numeric">{tasksCount}</td>
                    <td className="numeric">{punchlist}</td>
                    <td
                      className="numeric"
                      style={{ color: varianceColor, fontWeight: 500 }}
                    >
                      {varianceLabel}
                    </td>
                    <td className="muted" title={new Date(r.generated_at).toISOString()}>
                      {timeAgo(r.generated_at)}
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <Link
                        href={`/weekly-report/${r.id}`}
                        target="_blank"
                        rel="noreferrer"
                        style={{
                          color: 'var(--color-navy-700, #1F3864)',
                          fontWeight: 500,
                          textDecoration: 'none',
                        }}
                      >
                        View →
                      </Link>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
