-- ADR-030: Auth admin app_metadata is not visible to ordinary INSERT triggers.
--
-- Invitations therefore derive authority only from a server-created, hash-only
-- intent. Exact raw-user-metadata provisioning modes distinguish the benign
-- self-signup path from the invitation path before any tenant write occurs.

begin;

do $$
begin
  if to_regclass('public.tenants') is null
    or to_regclass('public.users') is null
    or to_regclass('public.audit_log') is null
    or to_regprocedure('public.audit_log_trigger()') is null then
    raise exception
      'ADR-030 requires tenants, users, audit_log, and audit_log_trigger() before apply'
      using errcode = '55000';
  end if;
end
$$;

-- Historical audit rows are evidence, not mutable operational state. This
-- closes the remaining privileged-write gap without modifying audit_log itself.
create or replace function public.reject_audit_log_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception 'audit_log is append-only'
    using errcode = '55000';
end;
$$;

revoke all on function public.reject_audit_log_mutation()
  from public, anon, authenticated;
grant execute on function public.reject_audit_log_mutation()
  to service_role;

drop trigger if exists audit_log_no_mutation on public.audit_log;
create trigger audit_log_no_mutation
  before update or delete on public.audit_log
  for each row execute function public.reject_audit_log_mutation();

-- The token is never persisted. `token_hash` is SHA-256 hex generated by the
-- trusted server from a cryptographically random 256-bit base64url token.
create table public.tenant_invitation_intents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null
    references public.tenants(id) on delete cascade,
  invited_email varchar(255) not null,
  invited_role public.role not null,
  invited_by uuid not null,
  created_by uuid not null,
  token_hash char(64) not null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  consumed_by_user_id uuid
    references auth.users(id) on delete restrict,
  revoked_at timestamptz,
  revoked_by uuid,
  revocation_reason text,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint tenant_invitation_intents_tenant_invited_by_fk
    foreign key (tenant_id, invited_by)
    references public.users(tenant_id, id)
    on delete restrict,
  constraint tenant_invitation_intents_tenant_created_by_fk
    foreign key (tenant_id, created_by)
    references public.users(tenant_id, id)
    on delete restrict,
  constraint tenant_invitation_intents_tenant_revoked_by_fk
    foreign key (tenant_id, revoked_by)
    references public.users(tenant_id, id)
    on delete restrict,
  constraint tenant_invitation_intents_inviter_is_creator
    check (invited_by = created_by),
  constraint tenant_invitation_intents_email_normalized
    check (
      invited_email = lower(btrim(invited_email))
      and length(invited_email) between 3 and 255
      and position('@' in invited_email) > 1
    ),
  constraint tenant_invitation_intents_token_hash_hex
    check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint tenant_invitation_intents_expiry_window
    check (
      expires_at > created_at
      and expires_at <= created_at + interval '24 hours'
    ),
  constraint tenant_invitation_intents_consumption_pair
    check (
      (consumed_at is null and consumed_by_user_id is null)
      or (consumed_at is not null and consumed_by_user_id is not null)
    ),
  constraint tenant_invitation_intents_terminal_state
    check (not (consumed_at is not null and revoked_at is not null)),
  constraint tenant_invitation_intents_revocation_actor
    check (
      (revoked_at is null and revoked_by is null and revocation_reason is null)
      or (
        revoked_at is not null
        and revoked_by is not null
        and revocation_reason = btrim(revocation_reason)
        and length(revocation_reason) > 0
      )
    )
);

create unique index ux_tenant_invitation_intents_tenant_id_id
  on public.tenant_invitation_intents (tenant_id, id);
create index idx_tenant_invitation_intents_tenant_state
  on public.tenant_invitation_intents (
    tenant_id,
    invited_email,
    expires_at,
    created_at desc
  );
create index idx_tenant_invitation_intents_invited_by
  on public.tenant_invitation_intents (tenant_id, invited_by, created_at desc);
create index idx_tenant_invitation_intents_created_by
  on public.tenant_invitation_intents (tenant_id, created_by, created_at desc);
create index idx_tenant_invitation_intents_revoked_by
  on public.tenant_invitation_intents (tenant_id, revoked_by)
  where revoked_by is not null;
create unique index ux_tenant_invitation_intents_token_hash
  on public.tenant_invitation_intents (token_hash);
create unique index ux_tenant_invitation_intents_consumed_auth_user
  on public.tenant_invitation_intents (consumed_by_user_id)
  where consumed_by_user_id is not null;
-- Auth identities are global. There may never be two simultaneously usable
-- invite capabilities for one normalized email, even across tenants.
create unique index ux_tenant_invitation_intents_active_email
  on public.tenant_invitation_intents (invited_email)
  where consumed_at is null and revoked_at is null;

-- Intent identities and terminal transitions are immutable. A server may only
-- revoke an unconsumed intent, and the auth trigger may only consume one.
create function public.enforce_tenant_invitation_intent_transition()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'Tenant invitation intents are append-only'
      using errcode = '55000';
  end if;

  if new.id is distinct from old.id
    or new.tenant_id is distinct from old.tenant_id
    or new.invited_email is distinct from old.invited_email
    or new.invited_role is distinct from old.invited_role
    or new.invited_by is distinct from old.invited_by
    or new.created_by is distinct from old.created_by
    or new.token_hash is distinct from old.token_hash
    or new.expires_at is distinct from old.expires_at
    or new.created_at is distinct from old.created_at then
    raise exception 'Tenant invitation intent identity is immutable'
      using errcode = '55000';
  end if;

  if old.consumed_at is not null or old.revoked_at is not null then
    raise exception 'Tenant invitation intent is already terminal'
      using errcode = '55000';
  end if;

  if new.consumed_at is not null then
    if new.consumed_by_user_id is null
      or new.revoked_at is not null
      or new.revoked_by is not null
      or new.revocation_reason is not null then
      raise exception 'Invalid tenant invitation intent consumption'
        using errcode = '22023';
    end if;
  elsif new.revoked_at is not null then
    if new.revoked_by is null
      or new.revocation_reason is null
      or new.consumed_by_user_id is not null then
      raise exception 'Invalid tenant invitation intent revocation'
        using errcode = '22023';
    end if;
  else
    raise exception 'Tenant invitation intents may only be consumed or revoked'
      using errcode = '55000';
  end if;

  new.updated_at := pg_catalog.clock_timestamp();
  return new;
end;
$$;

revoke all on function public.enforce_tenant_invitation_intent_transition()
  from public, anon, authenticated;
grant execute on function public.enforce_tenant_invitation_intent_transition()
  to service_role;

create trigger tenant_invitation_intents_enforce_transition
  before update or delete on public.tenant_invitation_intents
  for each row execute function public.enforce_tenant_invitation_intent_transition();

-- `audit_log_trigger()` serializes the audit chain. This custom emitter never
-- serializes the intent row, so neither the raw token nor its hash can enter
-- immutable audit evidence.
create function public.audit_tenant_invitation_intent()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text;
  v_actor_id uuid;
  v_diff jsonb;
  v_prev_hash text;
  v_created_at timestamptz := pg_catalog.clock_timestamp();
begin
  if tg_op = 'INSERT' then
    v_action := 'intent_created';
    v_actor_id := new.created_by;
    v_diff := pg_catalog.jsonb_build_object(
      'intent_id', new.id,
      'invited_role', new.invited_role::text
    );
  elsif new.consumed_at is distinct from old.consumed_at then
    v_action := 'intent_consumed';
    v_actor_id := new.invited_by;
    v_diff := pg_catalog.jsonb_build_object(
      'intent_id', new.id,
      'auth_user_id', new.consumed_by_user_id
    );
  elsif new.revoked_at is distinct from old.revoked_at then
    v_action := 'intent_revoked';
    v_actor_id := new.revoked_by;
    v_diff := pg_catalog.jsonb_build_object('intent_id', new.id);
  else
    raise exception 'Tenant invitation intent audit transition is invalid'
      using errcode = '55000';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('audit_log:' || new.tenant_id::text, 0)
  );

  select hash
    into v_prev_hash
    from public.audit_log
   where tenant_id = new.tenant_id
   order by id desc
   limit 1;

  if v_prev_hash is null then
    v_prev_hash := 'genesis';
  end if;

  insert into public.audit_log (
    tenant_id,
    actor_id,
    entity_type,
    entity_id,
    entity_key,
    action,
    diff,
    prev_hash,
    hash,
    created_at
  )
  values (
    new.tenant_id,
    v_actor_id,
    'tenant_invitation_intents',
    new.id,
    new.id::text,
    v_action,
    v_diff,
    v_prev_hash,
    pg_catalog.encode(
      extensions.digest(
        v_prev_hash
          || 'tenant_invitation_intents'
          || new.id::text
          || v_action
          || v_created_at::text,
        'sha256'
      ),
      'hex'
    ),
    v_created_at
  );

  return new;
end;
$$;

revoke all on function public.audit_tenant_invitation_intent()
  from public, anon, authenticated;
grant execute on function public.audit_tenant_invitation_intent()
  to service_role;

create trigger audit_tenant_invitation_intents
  after insert or update on public.tenant_invitation_intents
  for each row execute function public.audit_tenant_invitation_intent();

alter table public.tenant_invitation_intents enable row level security;
alter table public.tenant_invitation_intents force row level security;

revoke all privileges on table public.tenant_invitation_intents
  from public, anon, authenticated;
grant select, insert, update on table public.tenant_invitation_intents
  to service_role;

create policy deny_direct_client_access
  on public.tenant_invitation_intents
  for all
  to anon, authenticated
  using (false)
  with check (false);

comment on table public.tenant_invitation_intents is
  'ADR-030 server-only hash-only invitation authority; neither plaintext token nor hash is client-visible or audited.';

-- Audit actor injection is transaction-local and only set after the locked
-- intent revalidates its inviter against the legacy one-home-tenant authority.
create or replace function public.audit_log_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_action text;
  v_row jsonb;
  v_old_row jsonb;
  v_entity_key text;
  v_entity_id uuid;
  v_tenant_id uuid;
  v_actor_id uuid;
  v_invitation_actor_id text;
  v_diff jsonb;
  v_prev_hash text;
  v_created_at timestamptz := clock_timestamp();
begin
  v_old_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  v_row := case when tg_op = 'DELETE' then v_old_row else to_jsonb(new) end;
  v_action := case tg_op
    when 'INSERT' then 'create'
    when 'UPDATE' then 'update'
    when 'DELETE' then 'delete'
  end;

  v_tenant_id := nullif(v_row ->> 'tenant_id', '')::uuid;
  v_entity_key := coalesce(
    nullif(v_row ->> 'id', ''),
    nullif(concat_ws(':', v_row ->> 'tenant_id', v_row ->> 'sequence_key'), ''),
    nullif(v_row ->> 'subject_id', '')
  );

  if v_tenant_id is null or v_entity_key is null then
    raise exception 'Audit identity missing for %.%', tg_table_schema, tg_table_name;
  end if;

  if v_entity_key ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    v_entity_id := v_entity_key::uuid;
  else
    v_entity_id := public.audit_entity_uuid(tg_table_name, v_entity_key);
  end if;

  v_actor_id := auth.uid();
  if v_actor_id is null then
    v_invitation_actor_id := nullif(
      current_setting('app.tenant_invitation_v1_actor_id', true),
      ''
    );
    if v_invitation_actor_id is not null then
      v_actor_id := v_invitation_actor_id::uuid;
    end if;
  end if;

  v_diff := case
    when tg_op = 'UPDATE' then public.jsonb_diff(v_old_row, v_row)
    else v_row
  end;

  perform pg_advisory_xact_lock(
    hashtextextended('audit_log:' || v_tenant_id::text, 0)
  );

  select hash
    into v_prev_hash
    from public.audit_log
   where tenant_id = v_tenant_id
   order by id desc
   limit 1;

  if v_prev_hash is null then
    v_prev_hash := 'genesis';
  end if;

  insert into public.audit_log(
    tenant_id,
    actor_id,
    entity_type,
    entity_id,
    entity_key,
    action,
    diff,
    prev_hash,
    hash,
    created_at
  )
  values (
    v_tenant_id,
    v_actor_id,
    tg_table_name,
    v_entity_id,
    v_entity_key,
    v_action,
    v_diff,
    v_prev_hash,
    encode(
      digest(
        v_prev_hash
          || tg_table_name
          || v_entity_key
          || v_action
          || v_created_at::text,
        'sha256'
      ),
      'hex'
    ),
    v_created_at
  );

  return coalesce(new, old);
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_tenant_id uuid;
  intent public.tenant_invitation_intents%rowtype;
  provisioning_mode text;
  invitation_token text;
  invitation_token_hash text;
  has_invitation_token boolean;
  base_slug text;
  final_slug text;
  normalized_email text;
  domain text;
  tenant_name text;
  display_name text;
  new_organization_type text;
begin
  has_invitation_token := coalesce(
    new.raw_user_meta_data,
    '{}'::jsonb
  ) ? 'tenant_invitation_token_v1';
  provisioning_mode := new.raw_user_meta_data ->> 'provisioning_mode';

  normalized_email := pg_catalog.lower(
    coalesce(
      nullif(pg_catalog.btrim(new.email), ''),
      new.id::text || '@auth.local'
    )
  );

  if provisioning_mode = 'tenant_invitation_v1' then
    if not has_invitation_token then
      raise exception 'tenant invitation provisioning mode requires a token'
        using errcode = '22023';
    end if;

    invitation_token := new.raw_user_meta_data ->> 'tenant_invitation_token_v1';
    if pg_catalog.jsonb_typeof(
      new.raw_user_meta_data -> 'tenant_invitation_token_v1'
    ) <> 'string'
      or invitation_token !~ '^[A-Za-z0-9_-]{43}$' then
      raise exception 'invalid tenant invitation token'
        using errcode = '22023';
    end if;

    invitation_token_hash := pg_catalog.encode(
      extensions.digest(invitation_token, 'sha256'),
      'hex'
    );

    select *
      into intent
      from public.tenant_invitation_intents
     where token_hash = invitation_token_hash
     for update;

    if not found then
      raise exception 'unknown tenant invitation token'
        using errcode = '22023';
    end if;

    if intent.expires_at <= pg_catalog.clock_timestamp()
      or intent.revoked_at is not null
      or intent.consumed_at is not null then
      raise exception 'tenant invitation token is not usable'
        using errcode = '22023';
    end if;

    if intent.invited_email <> normalized_email then
      raise exception 'tenant invitation email does not match'
        using errcode = '42501';
    end if;

    if not exists (
      select 1
        from public.users inviter
       where inviter.id = intent.invited_by
         and inviter.tenant_id = intent.tenant_id
         and inviter.role in ('admin', 'owner')
    ) then
      raise exception 'tenant invitation inviter must be an owner or admin in the invited tenant'
        using errcode = '42501';
    end if;

    if exists (
      select 1
        from public.users
       where id = new.id
    ) then
      raise exception 'auth identity already has a profile'
        using errcode = '55000';
    end if;

    update public.tenant_invitation_intents
       set consumed_at = pg_catalog.clock_timestamp(),
           consumed_by_user_id = new.id
     where id = intent.id;

    -- The Auth row may later be exposed by an API response. Scrub the opaque
    -- capability before creating any application-visible profile.
    update auth.users
       set raw_user_meta_data = coalesce(
         raw_user_meta_data,
         '{}'::jsonb
       ) - 'tenant_invitation_token_v1'
     where id = new.id;

    display_name := pg_catalog.left(
      coalesce(
        nullif(
          pg_catalog.btrim(new.raw_user_meta_data ->> 'full_name'),
          ''
        ),
        nullif(
          pg_catalog.split_part(normalized_email, '@', 1),
          ''
        ),
        'New User'
      ),
      255
    );

    perform pg_catalog.set_config(
      'app.tenant_invitation_v1_actor_id',
      intent.invited_by::text,
      true
    );

    insert into public.users (
      id,
      tenant_id,
      email,
      full_name,
      role
    )
    values (
      new.id,
      intent.tenant_id,
      normalized_email,
      display_name,
      intent.invited_role
    );

    perform pg_catalog.set_config(
      'app.tenant_invitation_v1_actor_id',
      '',
      true
    );
    return new;
  end if;

  if provisioning_mode = 'self_signup_v1' then
    if has_invitation_token then
      raise exception 'self-signup provisioning mode cannot include an invitation token'
        using errcode = '22023';
    end if;
  else
    raise exception 'explicit valid provisioning mode is required'
      using errcode = '22023';
  end if;

  if exists (
    select 1
      from public.users
     where id = new.id
  ) then
    return new;
  end if;

  domain := nullif(
    pg_catalog.split_part(normalized_email, '@', 2),
    ''
  );
  tenant_name := pg_catalog.left(
    coalesce(
      nullif(
        pg_catalog.btrim(
          new.raw_user_meta_data ->> 'company_name'
        ),
        ''
      ),
      domain,
      'New Workspace'
    ),
    255
  );
  display_name := pg_catalog.left(
    coalesce(
      nullif(
        pg_catalog.btrim(
          new.raw_user_meta_data ->> 'full_name'
        ),
        ''
      ),
      nullif(
        pg_catalog.split_part(normalized_email, '@', 1),
        ''
      ),
      'New User'
    ),
    255
  );
  new_organization_type := case
    pg_catalog.lower(
      pg_catalog.btrim(
        coalesce(
          new.raw_user_meta_data ->> 'organization_type',
          ''
        )
      )
    )
    when 'construction' then 'construction'
    when 'developer' then 'developer'
    when 'design-engineering' then 'design-engineering'
    when 'supply-manufacturing' then 'supply-manufacturing'
    when 'professional-services' then 'professional-services'
    when 'other' then 'other'
    else 'other'
  end;

  base_slug := pg_catalog.regexp_replace(
    pg_catalog.lower(tenant_name),
    '[^a-z0-9]+',
    '-',
    'g'
  );
  base_slug := pg_catalog.btrim(base_slug, '-');
  base_slug := pg_catalog.btrim(
    pg_catalog.left(base_slug, 87),
    '-'
  );
  if base_slug = '' then
    base_slug := 'workspace';
  end if;

  final_slug :=
    base_slug
    || '-'
    || pg_catalog.substr(
      pg_catalog.md5(new.id::text),
      1,
      12
    );

  insert into public.tenants (
    name,
    slug,
    organization_type
  )
  values (
    tenant_name,
    final_slug,
    new_organization_type
  )
  returning id into new_tenant_id;

  insert into public.users (
    id,
    tenant_id,
    email,
    full_name,
    role
  )
  values (
    new.id,
    new_tenant_id,
    normalized_email,
    display_name,
    'admin'
  );

  return new;
end;
$$;

-- GoTrue can apply raw_user_meta_data in a later statement after the Auth
-- INSERT trigger commits its provisioning work. A consumed intent is the only
-- durable authority required to strip a replayed capability from that update.
create or replace function public.scrub_consumed_tenant_invitation_token()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.raw_user_meta_data ? 'tenant_invitation_token_v1'
    and exists (
      select 1
        from public.tenant_invitation_intents intent
       where intent.consumed_by_user_id = new.id
    ) then
    new.raw_user_meta_data := new.raw_user_meta_data
      - 'tenant_invitation_token_v1';
  end if;
  return new;
end;
$$;

revoke all on function public.scrub_consumed_tenant_invitation_token()
  from public, anon, authenticated;
grant execute on function public.scrub_consumed_tenant_invitation_token()
  to service_role;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists scrub_consumed_tenant_invitation_token on auth.users;
create trigger scrub_consumed_tenant_invitation_token
  before update of raw_user_meta_data on auth.users
  for each row execute function public.scrub_consumed_tenant_invitation_token();

revoke execute on function public.handle_new_user()
  from public, anon, authenticated;
grant execute on function public.handle_new_user()
  to service_role;

commit;
