import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ createSupabaseServerClient: vi.fn() }))
vi.mock('@third-code-erp/auth', () => ({ createSupabaseServerClient: mocks.createSupabaseServerClient }))
import { createProjectSubmittalThroughCoreApi, getProjectSubmittalsThroughCoreApi, mutateProjectSubmittalThroughCoreApi } from './erp-core-client'

const PROJECT_ID = '33333333-3333-4333-8333-333333333333'; const SUBMITTAL_ID = '44444444-4444-4444-8444-444444444444'; const REQUEST_ID = '55555555-5555-4555-8555-555555555555'; const USER_ID = '11111111-1111-4111-8111-111111111111'; const NOW = '2026-09-10T00:00:00.000Z'
const SUBMITTAL = { id: SUBMITTAL_ID, projectId: PROJECT_ID, submittalNumber: 'SUB-0001', title: 'HVAC shop drawing', description: 'Submit coordinated HVAC shop drawings.', specSection: '23 30 00', discipline: 'Mechanical', planReference: 'M-202', dueDate: '2026-09-18', status: 'draft' as const, submissionNotes: '', reviewNotes: '', rejectionReason: '', requestedBy: USER_ID, assignedTo: null, submittedAt: null, submittedBy: null, reviewStartedAt: null, reviewStartedBy: null, reviewedAt: null, reviewedBy: null, version: 1, createdAt: NOW, updatedAt: NOW }

describe('project submittals Core client', () => {
  beforeEach(() => { vi.restoreAllMocks(); vi.stubEnv('ERP_CORE_API_URL', 'https://core.example.test'); mocks.createSupabaseServerClient.mockResolvedValue({ auth: { getSession: vi.fn().mockResolvedValue({ data: { session: { access_token: 'token' } } }) } }); vi.stubGlobal('fetch', vi.fn()) })
  it('reads and validates a filtered register', async () => { vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({ projectId: PROJECT_ID, rows: [SUBMITTAL], total: 1, page: 1, limit: 25, totalPages: 1 }), { status: 200 })); await expect(getProjectSubmittalsThroughCoreApi(PROJECT_ID, { status: 'draft' })).resolves.toMatchObject({ ok: true, data: { total: 1 } }); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/submittals?status=draft&page=1&limit=25'), expect.objectContaining({ method: 'GET' })) })
  it('rejects invalid commands before network access', async () => { await expect(createProjectSubmittalThroughCoreApi({ projectId: PROJECT_ID })).resolves.toMatchObject({ ok: false, status: 400 }); expect(fetch).not.toHaveBeenCalled() })
  it('routes review target and validates a strict mutation envelope', async () => { vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({ projectId: PROJECT_ID, changed: true, submittal: { ...SUBMITTAL, status: 'under_review' as const, version: 2, submittedAt: NOW, submittedBy: USER_ID, reviewStartedAt: NOW, reviewStartedBy: USER_ID } }), { status: 200 })); await expect(mutateProjectSubmittalThroughCoreApi(PROJECT_ID, SUBMITTAL_ID, 'start-review', { expectedVersion: 1 })).resolves.toMatchObject({ ok: true, data: { submittal: { status: 'under_review' } } }); expect(fetch).toHaveBeenCalledWith(expect.stringContaining(`/submittals/${SUBMITTAL_ID}/start-review`), expect.objectContaining({ method: 'POST' })) })
  it('creates with stable request identity', async () => { vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({ projectId: PROJECT_ID, created: true, changed: true, submittal: SUBMITTAL }), { status: 201 })); await expect(createProjectSubmittalThroughCoreApi({ projectId: PROJECT_ID, clientRequestId: REQUEST_ID, title: SUBMITTAL.title, description: SUBMITTAL.description, specSection: SUBMITTAL.specSection, discipline: SUBMITTAL.discipline, planReference: SUBMITTAL.planReference, dueDate: SUBMITTAL.dueDate, assignedTo: null })).resolves.toMatchObject({ ok: true, data: { created: true } }); expect(fetch).toHaveBeenCalledWith(expect.stringContaining(`/projects/${PROJECT_ID}/submittals`), expect.objectContaining({ method: 'POST', body: expect.stringContaining(REQUEST_ID) })) })
})
